using System.Runtime.InteropServices.JavaScript;
using Polhem.UI.Core;

namespace Polhem.Northwind.Browser.Storage;

/// <summary>
/// <see cref="IEndpointStorage"/> / <see cref="IApiKeyStorage"/> implementation backed by the
/// browser's <c>window.localStorage</c>. The browser (WASM) runtime has no persistent file system,
/// so the default file-backed <see cref="FileEndpointStorage"/> would lose its writes on reload;
/// this persists the endpoint and the API key under per-app localStorage keys instead.
/// </summary>
/// <remarks>
/// Hosts opt in by assigning
/// <c>ClientInfo.EndpointStorage = new BrowserLocalStorageEndpointStorage("Polhem.Northwind");</c>
/// in the head's <c>Program.Main</c>, before any code calls
/// <see cref="ClientInfo.InitializeAsync(string, System.Threading.CancellationToken)"/> or <see cref="ClientInfo.SetEndpointAsync(string, System.Threading.CancellationToken)"/>.
/// <para>
/// Mirroring <see cref="FileEndpointStorage"/>, <see cref="SetEndpoint"/> mutates an in-memory cache
/// only; the localStorage entry is written solely by <see cref="SaveEndpoint"/> so a bound
/// input does not hit the JS boundary on every keystroke.
/// </para>
/// </remarks>
public sealed class BrowserLocalStorageEndpointStorage : IEndpointStorage, IApiKeyStorage
{
    private const string KeyPrefix = "Polhem.Endpoint.";
    private const string ApiKeyPrefix = "Polhem.ApiKey.";
    private readonly string _key;
    private readonly string _apiKeyKey;
    private string? _cachedEndpoint;
    private string? _cachedApiKey;

    /// <summary>
    /// Initializes a new instance of <see cref="BrowserLocalStorageEndpointStorage"/>.
    /// </summary>
    /// <param name="appName">
    /// Application name used to namespace the localStorage key. Must not be null or whitespace.
    /// </param>
    public BrowserLocalStorageEndpointStorage(string appName)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(appName);
        _key = KeyPrefix + appName;
        _apiKeyKey = ApiKeyPrefix + appName;
    }

    /// <inheritdoc/>
    public string LoadEndpoint()
    {
        _cachedEndpoint ??= LocalStorageInterop.GetItem(_key) ?? string.Empty;
        return _cachedEndpoint;
    }

    /// <inheritdoc/>
    public void SetEndpoint(string endpoint)
    {
        _cachedEndpoint = endpoint;
    }

    /// <inheritdoc/>
    public void SaveEndpoint(string endpoint)
    {
        _cachedEndpoint = endpoint;
        LocalStorageInterop.SetItem(_key, endpoint);
    }

    /// <inheritdoc/>
    public string LoadApiKey()
    {
        _cachedApiKey ??= LocalStorageInterop.GetItem(_apiKeyKey) ?? string.Empty;
        return _cachedApiKey;
    }

    /// <inheritdoc/>
    public void SetApiKey(string apiKey)
    {
        _cachedApiKey = apiKey;
    }

    /// <inheritdoc/>
    public void SaveApiKey(string apiKey)
    {
        _cachedApiKey = apiKey;
        LocalStorageInterop.SetItem(_apiKeyKey, apiKey);
    }
}

/// <summary>
/// Minimal JS interop binding to <c>window.localStorage</c> get / set, generated by the
/// browser-wasm <c>[JSImport]</c> source generator.
/// </summary>
internal static partial class LocalStorageInterop
{
    [JSImport("globalThis.localStorage.getItem")]
    internal static partial string? GetItem(string key);

    [JSImport("globalThis.localStorage.setItem")]
    internal static partial void SetItem(string key, string value);
}
